spring:
  application:
    name: accounts
  profiles:
    active: production
  datasource:
    url: ${accounts.datasource.url}
    username: ${accounts.datasource.username}
    password: ${accounts.datasource.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: ${accounts.datasource.database}
    hibernate:
      ddl-mode: ${accounts.datasource.ddl-mode}

management:
  endpoints:
    web:
      exposure:
        include: '*'

# ACTUATOR INFO
info:
  app:
    name: "Accounts"
    version: "0.0.1"
    profile: ${spring.profiles.active}
  serverInfo:
    port: ${server.port}

application:
  allow-get-accounts: ${accounts.allow-get-accounts}

eureka:
  client: ${eureka-client}