spring:
  application:
    name: accounts
  profiles:
    active: production
  datasource:
    url: ${accounts.datasource.url}
    username: ${accounts.datasource.username}
    password: ${accounts.datasource.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: ${accounts.datasource.database}
    hibernate:
      ddl-mode: ${accounts.datasource.ddl-mode}
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: ${spring.application.name}
      properties:
        spring.json.trusted.packages: "com.kodilla.commons"
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

management:
  endpoints:
    web:
      exposure:
        include: '*'

# ACTUATOR INFO
info:
  app:
    name: "Accounts"
    version: "0.0.1"
    profile: ${spring.profiles.active}
  serverInfo:
    port: ${server.port}

application:
  allow-get-accounts: ${accounts.allow-get-accounts}

eureka:
  client: ${eureka-client}

server:
  port: 9999